{
 "title": "Namada Blockchains",
 "description": "Internet of blockchains",
 "tags": [
  "Blockchain",
  "Cosmos"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "chain_id",
    "query": {
     "query": "label_values(up{job=\"namada-validator\"}, chain_id)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{chain_id=\"$chain_id\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$chain_id overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_consensus_latest_block_height{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_consensus_total_txs{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Avg Block Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "namada_tm_consensus_block_interval_seconds_count{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Bonded Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_consensus_byzantine_validators_power{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "namada_tm_consensus_validators{chain_id=\"$chain_id\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "namada_tm_consensus_missing_validators{chain_id=\"$chain_id\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "namada_tm_consensus_byzantine_validators{chain_id=\"$chain_id\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "namada_tm_consensus_validators_power{chain_id=\"$chain_id\"}",
     "legendFormat": "Online"
    },
    {
     "expr": "namada_tm_consensus_missing_validators_power{chain_id=\"$chain_id\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "namada_tm_consensus_byzantine_validators_power{chain_id=\"$chain_id\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "namada_tm_consensus_block_size_bytes{chain_id=\"$chain_id\"}",
     "legendFormat": "Block Size"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "namada_tm_consensus_num_txs{chain_id=\"$chain_id\"}",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "instance overview: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "namada_tm_p2p_peers{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Unconfirmed Transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "namada_tm_mempool_size{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Failed Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_mempool_failed_txs{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Recheck Times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_mempool_recheck_times{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Total Network Input",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "namada_tm_p2p_peer_receive_bytes_total{chain_id=\"$chain_id\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Total Network Output",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "namada_tm_p2p_peer_send_bytes_total{chain_id=\"$chain_id\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  }
 ]
}